config/routes.rb
Rails.application.routes.draw do

  resources :jobs  do
    get 'search/*query', to: 'jobs#index', as: :search, on: :collection
    match 'worker', to: 'jobs#worker', via:[:put, :patch]
    resources :bids
  end
  resources :showcases
  resources :articles
  resources :categories
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get 'projects',  to: 'static#myprojects'
  get 'get_subscategories' ,to: 'categories#get_subscategories'
  get 'get_newsubscategories' ,to: 'categories#get_subscategories'

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' , registrations: 'registrations'}
  devise_scope :user do
    get   'login',      :to => 'devise/sessions#new'
    post  'login',      :to => 'devise/sessions#new'
    get   'register',   :to => 'devise/registrations#new'
    post  'register',   :to => 'devise/registrations#new'
    delete 'logout',    to: 'devise/sessions#destroy'
    get   'password',   to: 'devise/passwords#new'
    get   'account',    to: 'registrations#edit'
    get   'u/:id' ,     to: 'users#show', :as => 'profile'
    get   'freelancers',to: 'users#index'

    authenticated :user do
      root 'jobs#index', as: :authenticated_root
    end

    unauthenticated do
      root 'frontend#index',    as: :unauthenticated_root
    end
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]



  def create
    @job = Job.find(params[:job_id])
    @bid =  @job.bids.build(bid_params)
    @bid.user = current_user
    if @bid.save
      redirect_to job_path(@job)
    end
  end


  def destroy
    @bid.user = current_user
    @bid.destroy
    redirect_to projects_url
  end

  private
  def set_bid
    @bid = Bid.find(params[:id])
  end

  def bid_params
    params.require(:bid).permit(:price,:time,:proposal)
  end

  def correct_user
    @bid = current_user.bids.find_by(id: params[:id])
    redirect_to job_path, notice: "Not authorized to destroy this comment" if @bid.nil?
  end
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_bids.html.erb
<% @job.bids.each do |bid|%>
    <%=bid.price%><br>
    <%= bid.time%><br>
    <%=bid.proposal%>
    <%= link_to 'Destroy', job_bid_path(@job.bids), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

app/views/bids/_form.html.erb
<h4 class="m-t-lg m-b">Bid on this project</h4>
<%= form_for([@job, @job.bids.build]) do |f| %>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price,class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :time %>
      <%= f.text_field :time,class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :proposal %>
      <%= f.text_area :proposal,class:'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'Submit Bid' , class:'btn btn-success'%>
    </div>
<% end %>