config/routes.rb
Rails.application.routes.draw do

  resources :jobs  do
    get 'search/*query', to: 'jobs#index', as: :search, on: :collection
    match 'worker', to: 'jobs#worker', via:[:put, :patch]
    resources :bids
  end
  resources :showcases
  resources :articles
  resources :categories
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get 'projects',  to: 'static#myprojects'
  get 'get_subscategories' ,to: 'categories#get_subscategories'
  get 'get_newsubscategories' ,to: 'categories#get_subscategories'

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' , registrations: 'registrations'}
  devise_scope :user do
    get   'login',      :to => 'devise/sessions#new'
    post  'login',      :to => 'devise/sessions#new'
    get   'register',   :to => 'devise/registrations#new'
    post  'register',   :to => 'devise/registrations#new'
    delete 'logout',    to: 'devise/sessions#destroy'
    get   'password',   to: 'devise/passwords#new'
    get   'account',    to: 'registrations#edit'
    get   'u/:id' ,     to: 'users#show', :as => 'profile'
    get   'freelancers',to: 'users#index'

    authenticated :user do
      root 'jobs#index', as: :authenticated_root
    end

    unauthenticated do
      root 'frontend#index',    as: :unauthenticated_root
    end
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/job.rb
class Job < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks


  has_attached_file :document
  validates_attachment :document, content_type: { content_type: "application/pdf" }


  belongs_to :category
  belongs_to :user
  has_many   :bids ,   :dependent => :destroy
  has_many   :taggings , :dependent => :destroy
  has_many   :tags, through: :taggings , :dependent => :destroy


  mapping do
    indexes :id, index: :not_analyzed
    indexes :title
    indexes :description
    indexes :price
    indexes :location
    indexes :duration
    indexes :categories, type: 'nested' do
      indexes :id,   type: 'integer'
      indexes :name, type: 'string', index: :not_analyzed
    end
    indexes :tags, type: 'nested' do
      indexes :id,   type: 'integer'
      indexes :name, type: 'string', index: :not_analyzed

    end
    indexes :users, type: 'nested' do
      indexes :id,   type: 'integer'
      indexes :name, type: 'string', index: :not_analyzed
    end
  end

#title, description , price, duration, location, category_id, document, tag_list, worker
  def as_indexed_json(options = {})
    self.as_json(only: [:id, :title, :description, :price, :location, :duration],
                 include: {
                     category:  { only: [:id, :name] },
                     tags: { only: [:id, :name], through: :taggings},
                     user: { only: [:id, :name] },
                 })
  end


  class << self
    def custom_search(query)
      __elasticsearch__.search(query: multi_match_query(query))
    end

    def multi_match_query(query)
      {
          multi_match: {
              query: query,
              type: "best_fields",
              fields: ["title^10", "description^8", "price", "price", "location^6", "categories.name^9","tags.name"],
              operator: "and" ,
          }
      }
    end
  end


  class RelationError < StandardError
    def initialize(msg = "That Relationship Type doesn't exist")
      super(msg)
    end
  end

  def add_many(type, data)
    if type.in? %w'category', 'bid', 'tags', 'user'
      # movie.genres = [data]
      self.send("#{type.downcase.pluralize}=", data.map do |g|
                                               type.classify.constantize.where(name: g).first_or_create!
                                             end)
    else
      raise RelationError
    end
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).jobs
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
        joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job ,only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_cat ,only:[:new, :edit, :update, :destroy,:create]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :beautify_search_url, only: [:index]


  def index
    query = params[:query].presence || "*"
    @jobs = Job.search(query).results
  end

  def new
  end

  def show
  end

  def create
    @job = current_user.jobs.build(jobs_params)
      if @job.save!
        redirect_to @job, notice: "Job Successfully Created"
      else
        render :new
      end
  end

  def edit

  end

  def worker
    @job = Job.find params[:job_id]
    @bid = Bid.find params[:bid_id]
    if @job.worker.nil?
      redirect_to projects_path if @job.update_attributes worker: @bid.user.id
    else
      redirect_to projects_path , notice: "#{@bid.user.name} assigned on this project"
    end
  end

  def update
    if @job.update(jobs_params)
      redirect_to job_path , notice: "Job Successfully Modified"
    else
      render :edit
    end
  end

  def destroy
     if @job.destroy!
       redirect_to projects_path
     else
       redirect_to job_path
     end
  end

  private

  def set_job
  @job = Job.find(params[:id])
  end

  def set_cat
    @job = current_user.jobs.build
  end

  def jobs_params
    params.require(:job).permit(:title,:description,:price,:duration,:location,:category_id,:document,:tag_list,:worker)
  end

  def correct_user
    @job = current_user.jobs.find_by_id(params[:id])
    redirect_to jobs_path, notice: "Not authorized to edit this job" if @job.nil?
  end

  def beautify_search_url
    redirect_to search_jobs_path(query: "#{params[:q]}") if params[:q].present?
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def categories
    @categories = Category.where(parent_id: nil)
  end
end

app/views/jobs/_form.html.erb
<div class="col-md-6">

  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        Option #one
      </div>
    </div>
    <div class="panel-body">
      <h5>
        Pages default style
      </h5>
      <div class="select2-container full-width">

        <%= form_for @job, :multipart => true do|f| %>

            <%= f.collection_select(:category_id, Category.where(parent_id: nil), :id, :name, {:prompt => 'Choose a category'},
                                    {class: "form-control"})%>

      </div>
        <div class="form-group form-group-default required ">
          <%=f.label :title%>
          <%=f.text_field :title,class:'form-control'%>
        </div>
        <div class="row">
          <div class="col-sm-12">
            <div class="form-group form-group-default required" style="height:250px">
              <%=f.label :description%>
              <%=f.text_area :description, class:'form-control', required: true, style:'height: 236px'%>
            </div>
          </div>
      </div>
        <div class="form-group bootstrap-tagsinput">
            <%= f.label :tag_list, "Skills" %><br />
            <%= f.text_field :tag_list, class:'tagsinput custom-tag-input', 'data-role'=>'tagsinput' %>
        </div>

    </div>
  </div>
</div>

<div class="col-md-6">

  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="panel-title">
        Option #one
      </div>
    </div>
    <div class="panel-body">
      <h5>
        Pages default style
      </h5>
      <div class="form-group form-group-default input-group">
        <%=f.label :price%>
        <%=f.text_field :price, class:'form-control'%>
        <span class="input-group-addon">Dinar</span>
      </div>
    <div class="form-group form-group-default input-group">
      <%=f.label :duration%>
      <%=f.text_field :duration, class:'form-control'%>
      <span class="input-group-addon">Days</span>
    </div>
    <div class="form-group  form-group-default required">
      <%=f.label :location%>
      <%=f.text_field :location, class:'form-control'%>
    </div>

      <div class="form-group  form-group-default">
        <%=f.label :document%>
        <%=f.file_field :document%>
      </div>
      <%=f.submit 'Submit',class:'btn btn-success'%>
    </div>
  </div>
</div>
<%end%>

app/views/jobs/_head.html.erb
    <div class="jumbotron sm vertical center bg-white column-w4 vertical-bottom no-margin" data-pages="parallax">
      <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20 full-height">
        <div class="inner text-center p-t-50 m-t-80 full-height">
          <p class="font-montserrat bold hint-text">Find Work</p>
          <div class="m-b-20">
            <h1 class="text-black inline">Jobs Matching My Skills</h1>
          </div>
          <div class="input-group padding-10 transparent col-md-5 b-b b-grey center-margin">

            <%= form_tag(jobs_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                <%= text_field_tag :q, params[:q], class: "form-control no-border", placeholder: "Search Articles" ,id:'widget-filter' do %>
               <span class="input-group-addon no-border" type="submit" >
                <i class="pg-search"></i>
                </span>
                <%end%>
                <%end%>
          </div>
          <div class="m-t-20 m-b-40 ">
            <p class="small hint-text">Only for purchased customers. See <a href="#">Terms &amp; Conditions</a>
            </p>
          </div>
        </div>
      </div>
    </div>

    <nav class="navbar navbar-default bg-master-lightest sm-padding-10" role="navigation">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sub-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="sub-nav">
          <div class="row">
            <div class="col-sm-10">
              <ul class="nav navbar-nav" data-filters="widgets">
               <%categories.each do |cat|%>
                <li><%= link_to cat.name, jobs_path(category: cat.name), class:'all-caps font-montserrat fs-11'%>
                </li>
                <%end%>
              </ul>
            </div>
            <div class="col-sm-2">
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a href="http://help.revox.io/" class="btn btn-default btn-sm padding-5 m-t-15">Suggest a widget
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </nav>

app/views/jobs/_job.html.erb
    <%= content_tag :div, class: 'col-sm-4', id: "job_#{job.id}" do %>
      <div class="panel panel-transparent">
        <div class="panel-body no-padding">
          <div id="portlet-advance" class="panel panel-default">
            <div class="panel-heading ">
              <div class="panel-title">
                <h3>
                  <span class="semi-bold"><%=job.title%></span></h3>
                Skills:
                <span class="label"><%=job.category.name%></span>
                Tags: <%= raw job.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
              </div>
              <div class="panel-controls">
                <ul>
                  <li><a href="#" class="portlet-maximize" data-toggle="maximize"><i class="portlet-icon portlet-icon-maximize"></i></a>
                  </li>
                  <li><a href="#" class="portlet-close" data-toggle="close"><i class="portlet-icon portlet-icon-close"></i></a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="panel-body">
              <p><b>Price</b> - <%=job.price%> ($$) - <b>Est. Time:</b> <%=job.duration%> - <b>Location: </b><%=job.location%></p>
              <p><%=job.description%></p>
              <div>
                <div class="profile-img-wrapper m-t-5 inline">
                  <img width="35" height="35" data-src-retina="assets/img/profiles/avatar_small2x.jpg" data-src="assets/img/profiles/avatar_small.jpg" alt="" src="assets/img/profiles/avatar_small2x.jpg">
                  <div class="chat-status available">
                  </div>
                </div>
                <div class="inline m-l-10">
                  <p class="small hint-text m-t-5">VIA senior product manage
                    <br>for UI/UX at REVOX</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<%end%>

app/views/jobs/_newsubcategories.html.erb
<%= f.collection_select(:category_id, Category.children, :id, :name, {:prompt => 'Choose a category'},
                        {class: "form-control"})%>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>
<%= render 'form'%>

app/views/jobs/index.html.erb
<%= provide(:title,'Freelance Jobs')%>

<%= render 'head'%>
<div class="container-fluid container-fixed-lg">
  <div class="panel panel-transparent">
    <div class="panel-heading">
    </div>
    <div class="panel-body">
      <div class="row">
        <%@jobs.each do |job|%>
            <%= render 'job', job: job%>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<%= provide(:title,'Post a Project')%>

<div class="page-content-wrapper ">

  <div class="content ">
        <div class="jumbotron" data-pages="parallax">
      <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
        <div class="inner">

          <ul class="breadcrumb">
            <li>
              <a href="#">Forms</a>
            </li>
            <li><a href="#" class="active">Form Elements</a>
            </li>
          </ul>

          <div class="row">
            <div class="col-lg-7 col-md-6 ">

              <div class="panel panel-default">
                <div class="panel-body text-center">
                  <img class="image-responsive-height demo-mw-600" src="assets/img/demo/form_hero.gif" alt="">
                </div>
              </div>

            </div>
            <div class="col-lg-5 col-md-6 ">

              <div class="panel panel-transparent">
                <div class="panel-heading">
                  <div class="panel-title">Getting started
                  </div>
                </div>
                <div class="panel-body">
                  <h3>One of the most underestimated elements of design is typography. However, it’s
                    critical in both print and web media. We Made it Perfect in both.</h3>
                  <br>
                  <div>
                    <div class="profile-img-wrapper m-t-5 inline">
                      <img width="35" height="35" src="assets/img/profiles/avatar_small.jpg" alt="" data-src="assets/img/profiles/avatar_small.jpg" data-src-retina="assets/img/profiles/avatar_small2x.jpg">
                      <div class="chat-status available">
                      </div>
                    </div>
                    <div class="inline m-l-10">
                      <p class="small hint-text m-t-5">VIA senior product manage
                        <br> for UI/UX at REVOX</p>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid container-fixed-lg">
      <div class="row">
        <%= render 'form'%>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<h1>Job</h1>
<%=@job.title%>
<%=@job.description%>
<%=@job.price%>
<%=@job.location%>
<%=@job.duration%>

<%= link_to 'Destroy', @job , method: :delete, data: { confirm: 'Are you sure?' } %>

<%= render 'bids/form'%>
<%= render 'bids/bids'%>