config/routes.rb
Rails.application.routes.draw do

  resources :jobs  do
    get 'search/*query', to: 'jobs#index', as: :search, on: :collection
    match 'worker', to: 'jobs#worker', via:[:put, :patch]
    resources :bids
  end
  resources :showcases
  resources :articles
  resources :categories
  get 'tags/:tag', to: 'jobs#index', as: :tag
  get 'projects',  to: 'static#myprojects'
  get 'get_subscategories' ,to: 'categories#get_subscategories'
  get 'get_newsubscategories' ,to: 'categories#get_subscategories'

  devise_for :users, :controllers => { :omniauth_callbacks => 'callbacks' , registrations: 'registrations'}
  devise_scope :user do
    get   'login',      :to => 'devise/sessions#new'
    post  'login',      :to => 'devise/sessions#new'
    get   'register',   :to => 'devise/registrations#new'
    post  'register',   :to => 'devise/registrations#new'
    delete 'logout',    to: 'devise/sessions#destroy'
    get   'password',   to: 'devise/passwords#new'
    get   'account',    to: 'registrations#edit'
    get   'u/:id' ,     to: 'users#show', :as => 'profile'
    get   'freelancers',to: 'users#index'

    authenticated :user do
      root 'jobs#index', as: :authenticated_root
    end

    unauthenticated do
      root 'frontend#index',    as: :unauthenticated_root
    end
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/layouts/common/_footer.html.erb
<section class="p-b-55 p-t-75 xs-p-b-20 bg-master-darker ">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-xs-12 xs-m-b-40">
        <img src="assets/images/logo_white.png" data-src-retina="assets/images/logo_white_2x.png" class="alt" alt="" height="21" width="152">
      </div>
      <div class="col-sm-2 col-xs-6 xs-m-b-20">
        <h6 class="font-montserrat text-uppercase fs-14 text-white p-b-10">Company </h6>
        <ul class="no-style">
          <li class="m-b-5 no-padding"><a href="#" class="link text-white ">Design</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Features</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Team</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Work Station</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Privacy</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Legal</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Jobs</a></li>
        </ul>
      </div>
      <div class="col-sm-2 col-xs-6 xs-m-b-20">
        <h6 class="font-montserrat text-uppercase fs-14 text-white p-b-10">Work </h6>
        <ul class="no-style">
          <li class="m-b-5 no-padding"><a href="#" class="link text-white ">Apps</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white ">Popular</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white ">Web-Arch</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Pages</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Frontend</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Charity</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Marketplaces</a></li>
        </ul>
      </div>
      <div class="col-sm-2 col-xs-6 xs-m-b-20">
        <h6 class="font-montserrat text-uppercase fs-14 text-white p-b-10">Clients </h6>
        <ul class="no-style">
          <li class="m-b-5 no-padding"><a href="#" class="link text-white ">Our team</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Our location</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Contact Us</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">About Us</a></li>
        </ul>
      </div>
      <div class="col-sm-2 col-xs-6 xs-m-b-20">
        <h6 class="font-montserrat text-uppercase fs-14 text-white p-b-10">Pages </h6>
        <ul class="no-style">
          <li class="m-b-5 no-padding"><a href="#" class="link text-white ">Pages</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Home</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Tour</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Versions</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Dropdown</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Pricing Page</a></li>
          <li class="m-b-5 no-padding"><a href="#" class="link text-white">Blog</a></li>
        </ul>
      </div>
    </div>
    <p class="fs-12 hint-text p-t-10 text-white">Copyright © 2014. All Rights Reserved </p>
  </div>
</section>

app/views/layouts/common/_head.html.erb
  <div class="header ">

    <div class="container-fluid relative">

      <div class="pull-left full-height visible-sm visible-xs">

        <div class="header-inner">
          <a href="#" class="btn-link toggle-sidebar visible-sm-inline-block visible-xs-inline-block padding-5" data-toggle="sidebar">
            <span class="icon-set menu-hambuger"></span>
          </a>
        </div>

      </div>
      <div class="pull-center hidden-md hidden-lg">
        <div class="header-inner">
          <div class="brand inline">
            <img src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">
          </div>
        </div>
      </div>

      <div class="pull-right full-height visible-sm visible-xs">

        <div class="header-inner">
          <a href="#" class="btn-link visible-xs-inline-block visible-sm-inline-block m-r-10" data-pages="horizontal-menu-toggle">
            <span class="pg pg-arrow_minimize"></span>
          </a>
          <a href="#" class="btn-link visible-sm-inline-block visible-xs-inline-block" data-toggle="quickview" data-toggle-element="#quickview">
            <span class="icon-set menu-hambuger-plus"></span>
          </a>
        </div>

      </div>
    </div>

    <div class=" pull-left sm-table hidden-xs hidden-sm">
      <div class="header-inner">
        <div class="brand inline">
          <img src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">
        </div>

        <ul class="notification-list no-margin hidden-sm hidden-xs b-grey b-l b-r no-style p-l-30 p-r-20">
          <li class="p-r-15 inline">
            <div class="dropdown">
              <a href="javascript:;" id="notification-center" class="icon-set globe-fill" data-toggle="dropdown">
                <span class="bubble"></span>
              </a>

              <div class="dropdown-menu notification-toggle" role="menu" aria-labelledby="notification-center">

                <div class="notification-panel">

                  <div class="notification-body scrollable">
                    <%notification.order("id DESC").each do |job|%>
                    <div class="notification-item unread clearfix">
                      <div class="heading">
                        <div class="thumbnail-wrapper d24 circular b-white m-r-5 b-a b-white m-t-10 m-r-10">
                          <%= image_tag job.user.image, width: 30, height: 30%>
                        </div>
                        <a href="#" class="text-complete pull-left">
                          <span class="bold"><%=job.title%></span>
                        </a>
                        <span class="pull-right time"><%="#{time_ago_in_words(job.created_at)} ago"%></span>
                      </div>

                      <div class="option" data-toggle="tooltip" data-placement="left" title="mark as read">
                        <a href="#" class="mark"></a>
                      </div>

                    </div>
                    <%end%>
                  </div>


                  <div class="notification-footer text-center">
                    <a href="#" class="">Read all notifications</a>
                    <a data-toggle="refresh" class="portlet-refresh text-black pull-right" href="#">
                      <i class="pg-refresh_new"></i>
                    </a>
                  </div>

                </div>

              </div>

            </div>
          </li>
          <li class="p-r-15 inline">
            <a href="#" class="icon-set clip "></a>
          </li>
          <li class="p-r-15 inline">
            <a href="#" class="icon-set grid-box"></a>
          </li>
        </ul>

        <a href="#" class="search-link" data-toggle="search"><i class="pg-search"></i>Type anywhere to <span class="bold">search</span></a> </div>
    </div>
    <div class=" pull-right">
      <div class="header-inner">
        <a href="#" class="btn-link icon-set menu-hambuger-plus m-l-20 sm-no-margin hidden-sm hidden-xs" data-toggle="quickview" data-toggle-element="#quickview"></a>
      </div>
    </div>
    <div class=" pull-right">

      <div class="visible-lg visible-md m-t-10">
        <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
          <span class="semi-bold"><%=current_user.name%></span>
        </div>
        <div class="dropdown pull-right">
          <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="thumbnail-wrapper d32 circular inline m-t-5">
            <%= image_tag current_user.image, width: 32, height: 32 %>
            </span>
          </button>
          <ul class="dropdown-menu profile-dropdown" role="menu">
            <li>
              <%=link_to account_path do %>
                 <i class="pg-settings_small"></i> Settings
              <%end%>
            </li>
            <li><a href="#"><i class="pg-outdent"></i> Feedback</a>
            </li>
            <li><a href="#"><i class="pg-signals"></i> Help</a>
            </li>
            <li class="bg-master-lighter clearfix">
                <%= link_to  destroy_user_session_path, method: :delete do %>
                <span class="pull-left">Logout</span>
                <span class="pull-right"><i class="pg-power"></i></span>
                <%end%>
            </li>
          </ul>
        </div>
      </div>

    </div>
  </div>

  <div class="page-content-wrapper ">

    <div class="content ">
      <div class="bar">
        <div class="pull-right">
          <a href="#" class="text-black padding-10 visible-xs-inline visible-sm-inline pull-right m-t-10 m-b-10 m-r-10 on" data-pages="horizontal-menu-toggle">
            <i class=" pg-close_line"></i>
          </a>
        </div>
        <div class="bar-inner">
          <ul>
            <li class="classic">
              <a href="javascript:;">
                Find Freelancer <span class="arrow"></span>
              </a>
              <ul class="classic">
                <li>
                  <%= link_to 'Start a Project ', new_job_path%>
                </li>
                <li>
                  <%= link_to 'Find Freelancer', freelancers_path%>
                </li>
                <li>
                  <%= link_to 'Showcases', showcases_path%>
                </li>
                <li>
                  <a href="#">Community Project</a>
                </li>
              </ul>
            </li>

            <li class="classic">
              <a href="javascript:;">
                Find Work <span class="arrow"></span>
              </a>
              <ul class="classic">
                <li>
                  <%=link_to 'Browse Projects', jobs_path%>
                </li>
                <li>
                  <%=link_to 'Browse Categories', categories_path%>
                </li>
                <li>
                  <a href="#">Community Project</a>
                </li>
              </ul>
            </li>
            <li class="classic">
              <%=link_to 'My Projects', projects_path%>
            </li>
          </ul>
        </div>
      </div>
      </div>
    </div>

app/views/layouts/common/_notifications.html.erb
<%if notice %>
    <div class="pgn-wrapper" data-position="top-right">
      <div class="pgn pgn-circle">
        <div class="alert alert-success">
          <div>
            <div class="pgn-thumbnail">
              <div>
                <%= image_tag current_user.image, width: 40, height: 40, style:'display: inline-block' %>
              </div>
            </div>
            <div class="pgn-message">
              <div>
                <p class="bold"><%=current_user.name%></p>
                <p><%= notice %></p>
              </div>
            </div>
          </div>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
          </button>
        </div>
      </div>
    </div>
<%elsif alert %>
    <div class="pgn-wrapper" data-position="top-right">
      <div class="pgn pgn-circle">
        <div class="alert alert-danger">
          <div>
            <div class="pgn-thumbnail">
              <div>
                <%= image_tag current_user.image, width: 40, height: 40, style:'display: inline-block' %>
              </div>
            </div>
            <div class="pgn-message">
              <div>
                <p class="bold"><%=current_user.name%></p>
                <p><%= alert %></p>
              </div>
            </div>
          </div>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span>
            <span class="sr-only">Close</span>
          </button>
        </div>
      </div>
    </div>
<%end%>

app/views/layouts/common/_search.html.erb
<div class="overlay hide" data-pages="search">

  <div class="overlay-content has-results m-t-20">

    <div class="container-fluid">

      <img class="overlay-brand" src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">


      <a href="#" class="close-icon-light overlay-close text-black fs-16">
        <i class="pg-close"></i>
      </a>

    </div>

    <div class="container-fluid">

      <input id="overlay-search" class="no-border overlay-search bg-transparent" placeholder="Search..." autocomplete="off" spellcheck="false">
      <br>
      <div class="inline-block">
        <div class="checkbox right">
          <input id="checkboxn" type="checkbox" value="1" checked="checked">
          <label for="checkboxn"><i class="fa fa-search"></i> Search within page</label>
        </div>
      </div>
      <div class="inline-block m-l-10">
        <p class="fs-13">Press enter to search</p>
      </div>

    </div>

    <div class="container-fluid">
<span>
<strong>suggestions :</strong>
</span>
      <span id="overlay-suggestions"></span>
      <br>
      <div class="search-results m-t-40">
        <p class="bold">Pages Search Results</p>
        <div class="row">
          <div class="col-md-6">

            <div class="">

              <div class="thumbnail-wrapper d48 circular bg-success text-white inline m-t-10">
                <div>
                  <img width="50" height="50" src="assets/img/profiles/avatar.jpg" data-src="assets/img/profiles/avatar.jpg" data-src-retina="assets/img/profiles/avatar2x.jpg" alt="">
                </div>
              </div>

              <div class="p-l-10 inline p-t-5">
                <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> on pages</h5>
                <p class="hint-text">via john smith</p>
              </div>
            </div>


            <div class="">

              <div class="thumbnail-wrapper d48 circular bg-success text-white inline m-t-10">
                <div>T</div>
              </div>

              <div class="p-l-10 inline p-t-5">
                <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> related topics</h5>
                <p class="hint-text">via pages</p>
              </div>
            </div>


            <div class="">

              <div class="thumbnail-wrapper d48 circular bg-success text-white inline m-t-10">
                <div><i class="fa fa-headphones large-text "></i>
                </div>
              </div>

              <div class="p-l-10 inline p-t-5">
                <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> music</h5>
                <p class="hint-text">via pagesmix</p>
              </div>
            </div>

          </div>
          <div class="col-md-6">

            <div class="">

              <div class="thumbnail-wrapper d48 circular bg-info text-white inline m-t-10">
                <div><i class="fa fa-facebook large-text "></i>
                </div>
              </div>

              <div class="p-l-10 inline p-t-5">
                <h5 class="m-b-5"><span class="semi-bold result-name">ice cream</span> on facebook</h5>
                <p class="hint-text">via facebook</p>
              </div>
            </div>


            <div class="">

              <div class="thumbnail-wrapper d48 circular bg-complete text-white inline m-t-10">
                <div><i class="fa fa-twitter large-text "></i>
                </div>
              </div>

              <div class="p-l-10 inline p-t-5">
                <h5 class="m-b-5">Tweats on<span class="semi-bold result-name"> ice cream</span></h5>
                <p class="hint-text">via twitter</p>
              </div>
            </div>


            <div class="">

              <div class="thumbnail-wrapper d48 circular text-white bg-danger inline m-t-10">
                <div><i class="fa fa-google-plus large-text "></i>
                </div>
              </div>

              <div class="p-l-10 inline p-t-5">
                <h5 class="m-b-5">Circles on<span class="semi-bold result-name"> ice cream</span></h5>
                <p class="hint-text">via google plus</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

  </div>

</div>